spring:
  application:
    name: payment

  datasource:
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false


PSP:
  toss:
    secret-key: test_sk_ma60RZblrqBKkpLaLQxR8wzYWBn1
    url: https://api.tosspayments.com