spring:
  application:
    name: payment

  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false


PSP:
  toss:
    secret-key: test_sk_ma60RZblrqBKkpLaLQxR8wzYWBn1
    url: https://api.tosspayments.com